export enum TemplateActionType {
    USER_FIND_TEMPLATE = 'USER_FIND_TEMPLATE',
    USER_ADD_TEMPLATE = 'USER_ADD_TEMPLATE',
    USER_UPDATE_TEMPLATE = 'USER_UPDATE_TEMPLATE',
    USER_DELETE_TEMPLATE = 'USER_DELETE_TEMPLATE',
}
