export enum TemplateActionType {
    USER_FIND_TEMPLATE = 'USER_FIND_TEMPLATE',
    USER_ADD_TEMPLATE = 'USER_ADD_TEMPLATE',
    USER_UPDATE_TEMPLATE = 'USER_UPDATE_TEMPLATE',
    USER_DELETE_TEMPLATE = 'USER_DELETE_TEMPLATE',
    USER_QUERY_TEMPLATE = 'USER_QUERY_TEMPLATE',
    USER_CLEAR_TEMPLATE = 'USER_CLEAR_TEMPLATE',
    USER_ADD_TOOLBAR_BLOCK = 'USER_ADD_TOOLBAR_BLOCK',
    USER_ADD_EDITING_SURFACE_BLOCK = 'USER_ADD_EDITING_SURFACE_BLOCK',
    USER_UPDATE_BLOCK = 'USER_UPDATE_BLOCK',
    USER_DELETE_BLOCK = 'USER_DELETE_BLOCK',
}
