version: '3.8'
services:
    development:
        build: ./
        container_name: pushpull-client
        ports:
            - '3000:3000'
        volumes:
            - './:/app'
        environment:
            - NODE_ENV=development
        stdin_open: true
        tty: true
    test:
        build: ./
        container_name: pushpull-client-test
        environment:
            - CI=true
        command: npm test
