export enum uiLoaderActionType {
    START_TEMPLATE_BLOCK_LOADER = 'START_TEMPLATE_BLOCK_LOADER',
    END_TEMPLATE_BLOCK_LOADER = 'START_TEMPLATE_BLOCK_LOADER',
    START_MAINBUILDTEMPLATEVIEW_LOADER = 'START_MAINBUILDTEMPLATEVIEW_LOADER',
    END_MAINBUILDTEMPLATEVIEW_LOADER = 'END_MAINBUILDTEMPLATEVIEW_LOADER',
    START_ADDBLOCKMODAL_LOADER = 'START_ADDBLOCKMODAL_LOADER',
    END_ADDBLOCKMODAL_LOADER = 'END_ADDBLOCKMODAL_LOADER',
    START_GLOBALSETTINGSMODAL_LOADER = 'START_GLOBALSETTINGSMODAL_LOADER',
    END_GLOBALSETTINGSMODAL_LOADER = 'END_GLOBALSETTINGSMODAL_LOADER',
}
