export enum uiLoaderActionType {
    START_MAINBUILDTEMPLATEVIEW_LOADER = 'START_MAINBUILDTEMPLATEVIEW_LOADER',
    END_MAINBUILDTEMPLATEVIEW_LOADER = 'END_MAINBUILDTEMPLATEVIEW_LOADER',
    START_ADDBLOCKMODAL_LOADER = 'START_ADDBLOCKMODAL_LOADER',
    END_ADDBLOCKMODAL_LOADER = 'END_ADDBLOCKMODAL_LOADER',
}
