export enum ReviewActionType {
    USER_GET_REVIEWS = 'USER_GET_REVIEWS',
    USER_UPDATE_REVIEWS = 'USER_UPDATE_REVIEWS',
    USER_CREATE_REVIEWS = 'USER_CREATE_REVIEWS',
    USER_DELETE_REVIEWS = 'USER_DELETE_REVIEWS',
}
