export enum loaderTypes {
    LOAD_ALL_TEMPLATE_BLOCKS = 'LOAD_ALL_TEMPLATE_BLOCKS',
    MAIN_BUILD_TEMPLATE_VIEW = 'MAIN_BUILD_TEMPLATE_VIEW',
    ADD_BLOCK_MODAL = 'ADD_BLOCK_MODAL',
    GLOBAL_SETTINGS_MODAL = 'GLOBAL_SETTINGS_MODAL',
    VIEWER_INTERACTIONS_SETTINGS_MODAL = 'VIEWER_INTERACTIONS_SETTINGS_MODAL',
}
