export enum ModalActionTypes {
    DELETE_SHEET_CONFIRMATION = 'DELETE_SHEET_CONFIRMATION',
    ADD_COLOR_SWATCH_POPOVER = 'ADD_COLOR_SWATCH_POPOVER',
    DELETE_COLOR_SWATCH_POPOVER = 'DELETE_COLOR_SWATCH_POPOVER',
    ADD_VIEWER_INPUT_POPOVER = 'ADD_VIEWER_INPUT_POPOVER',
    DELETE_VIEWER_INPUT_POPOVER = 'DELETE_VIEWER_INPUT_POPOVER',
}
