export enum WorkoutProgramActionType {
    USER_GET_WORKOUTPROGRAMS = 'USER_GET_WORKOUTPROGRAMS',
    USER_UPDATE_WORKOUTPROGRAM = 'USER_UPDATE_WORKOUTPROGRAM',
    USER_CREATE_WORKOUTPROGRAM = 'USER_CREATE_WORKOUTPROGRAM',
    USER_DELETE_WORKOUTPROGRAM = 'USER_DELETE_WORKOUTPROGRAM',
}
