export enum FilterActionType {
    USER_UPDATE_CATEGORY = 'USER_UPDATE_CATEGORY',
    USER_UPDATE_EQUIPMENT = 'USER_UPDATE_EQUIPMENT',
    USER_UPDATE_DIFFICULTY = 'USER_UPDATE_DIFFICULTY',
    USER_UPDATE_WORKOUTSCHEDULE = 'USER_UPDATE_WORKOUTSCHEDULE',
    USER_UPDATE_WORKOUTLENGTH = 'USER_UPDATE_WORKOUTLENGTH',
}
